spring.application.name=smart-habit-tracker

spring.datasource.url=jdbc:mysql://localhost:3306/habit_tracker?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8080

jwt.secretKey = jsdf9384i930849ieowpfj4euk464h9gawfe6y4thrgsuythd65gs6